export const PUBLIC_SITE_ORIGIN = 'https://ui.magguu.xyz'

export const SITE_SETTINGS_DEFAULTS: Record<string, string> = {
  site_name: 'MagguuUI',
  site_description: 'World of Warcraft UI Configuration',
  curseforge_url: '',
  github_url: 'https://github.com/Derpsen/MagguuUI',
  discord_url: '',
  maintenance_mode: 'false',
  banner_text: '',
  meta_title: 'MagguuUI - Your WoW Interface, perfected.',
  meta_description: 'High-quality import strings for ElvUI, Plater, BigWigs, Details and more. Simply copy and paste into WoW.',
  og_image_url: 'https://ui.magguu.xyz/logo.png',
  contact_email: 'contact@magguui.com',
  imprint_name: '',
  imprint_street: '',
  imprint_city: '',
  imprint_country: 'Germany',
  session_timeout_hours: '24',
  max_login_attempts: '10',
  lockout_duration_minutes: '30',
  tracking_pageviews_enabled: 'true',
  tracking_copyevents_enabled: 'true',
  data_retention_days: '90',
}

export const PUBLIC_SITE_SETTING_KEYS = [
  'site_name',
  'site_description',
  'github_url',
  'discord_url',
  'curseforge_url',
  'banner_text',
  'maintenance_mode',
  'meta_title',
  'meta_description',
  'og_image_url',
  'contact_email',
  'imprint_name',
  'imprint_street',
  'imprint_city',
  'imprint_country',
] as const

export const PUBLIC_SITE_SETTINGS_DEFAULTS: Record<string, string> = {
  site_name: SITE_SETTINGS_DEFAULTS.site_name,
  site_description: SITE_SETTINGS_DEFAULTS.site_description,
  github_url: SITE_SETTINGS_DEFAULTS.github_url,
  discord_url: SITE_SETTINGS_DEFAULTS.discord_url,
  curseforge_url: SITE_SETTINGS_DEFAULTS.curseforge_url,
  banner_text: SITE_SETTINGS_DEFAULTS.banner_text,
  maintenance_mode: SITE_SETTINGS_DEFAULTS.maintenance_mode,
  meta_title: SITE_SETTINGS_DEFAULTS.meta_title,
  meta_description: SITE_SETTINGS_DEFAULTS.meta_description,
  og_image_url: SITE_SETTINGS_DEFAULTS.og_image_url,
  contact_email: SITE_SETTINGS_DEFAULTS.contact_email,
  imprint_name: SITE_SETTINGS_DEFAULTS.imprint_name,
  imprint_street: SITE_SETTINGS_DEFAULTS.imprint_street,
  imprint_city: SITE_SETTINGS_DEFAULTS.imprint_city,
  imprint_country: SITE_SETTINGS_DEFAULTS.imprint_country,
}
